public class Calculator {
    public void printNewMessage(string msg){
        System.debug(msg);
    }
    public string printAndReturnMessage(string msg){
        string returnStr = msg + '...OK Cool';
        return returnStr;
    }
    // public string printAndReturnMessage(string msg){
    //     string returnStr = msg + '...OK Cool';
    //     return returnStr;
    // }
    // public string print(){
    //     integer result= msg;
    //     return 'wohoo';
    // }
}
